name: Bool trigger pass job triggers
on:
  # Permit targeted manual trigger within console
  workflow_dispatch:
    inputs:
      change-trigger:
        description: Trigger steps and jobs
        type: boolean
        default: false

jobs:
  
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      TRIGGER_DOWNSTREAM_JOBS: ${{ steps.set-output.outputs.TRIGGER_DOWNSTREAM_JOBS }}
    steps:
    - name: Stuff
      id: set-output
      run: |
        echo "hi"
        #echo "${{ inputs.change-trigger }}" # true
        echo "TRIGGER_DOWNSTREAM_JOBS=${{ inputs.change-trigger }}" >> $GITHUB_OUTPUT

    - name: Run only when changes true
      # Run only when tf-changes is true
      if: steps.tf-changes.outputs.TRIGGER_DOWNSTREAM_JOBS == 'true'
      id: downstream-step
      run: |
        echo "This one isn't used, even though it's the same variable name"
        echo "Note how the Job output is fetched from a specific step name"
        echo "TRIGGER_DOWNSTREAM_JOBS=false" >> $GITHUB_OUTPUT

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    # Run only when there are TF changes
    if: |
      needs.job1.outputs.TRIGGER_DOWNSTREAM_JOBS == 'true'
    steps:
    - name: Stuff
      id: set-deploy-strategy
      run: |
        echo "hi"  
