# This job is run manually, and takes a boolean input (true/false) of whether to trigger a specific task in Job 1
# That job sets a variable that is exported from the job, and is read by a downstream Job
# That downstream Job will only run if job1.step2 runs and sets an output variable to true

name: Bool input triggers steps, jobs

on:
  workflow_dispatch:
    inputs:
      trigger-job1-step2:
        description: Trigger job1, step2
        type: boolean
        default: false

jobs:
  
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      TRIGGER_JOB2: ${{ steps.step2.outputs.TRIGGER_JOB2 }}
    steps:
    - name: Stuff
      id: set-output
      run: |
        echo "hi"
        echo "${{ inputs.trigger-job1-step2 }}" # true or false
        
    - name: Run only when changes true
      # Run only when trigger-job1-step2 is true
      if: |
        inputs.trigger-job1-step2 == true
      id: step2
      run: |
        echo "TRIGGER_JOB2=true" >> $GITHUB_OUTPUT

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    # Run only when job1 indicates to run
    if: |
      needs.job1.outputs.TRIGGER_JOB2 == 'true'
    steps:
    - name: Stuff
      run: |
        echo "hi"  
