name: Bool trigger pass job triggers
on:
  # Permit targeted manual trigger within console
  workflow_dispatch:
    inputs:
      trigger-job1-step2:
        description: Trigger job1, step2
        type: boolean
        default: false

jobs:
  
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      TRIGGER_DOWNSTREAM_JOBS: ${{ steps.step2.outputs.TRIGGER_DOWNSTREAM_JOBS }}
    steps:
    - name: Stuff
      id: set-output
      run: |
        echo "hi"
        echo "${{ inputs.trigger-job1-step2 }}" # true or false
        
    - name: Run only when changes true
      # Run only when TRIGGER_DOWNSTREAM_JOBS is true
      if: |
        inputs.trigger-job1-step2 == true
      id: step2
      run: |
        echo "TRIGGER_DOWNSTREAM_JOBS=${{ inputs.trigger-job1-step2 }}" >> $GITHUB_OUTPUT

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    # Run only when there are TF changes
    if: |
      needs.job1.outputs.TRIGGER_DOWNSTREAM_JOBS == 'true'
    steps:
    - name: Stuff
      id: set-deploy-strategy
      run: |
        echo "hi"  
