name: Multiple condition validation
on:
  # Permit targeted manual trigger within console
  workflow_dispatch:
    inputs:
      change-trigger:
        description: Trigger steps and jobs
        type: boolean
        default: false

jobs:
  
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      TF_CHANGES: ${{ steps.tf-changes.outputs.TF_CHANGES }}
    steps:
    - name: Stuff
      id: tf-changes
      run: |
        echo "hi"
        echo "TF_CHANGES=${{ inputs.change-trigger }}" >> $GITHUB_OUTPUT

    - name: Run only when changes true
      # Run only when tf-changes is true
      if: steps.tf-changes.outputs.TF_CHANGES == 'true'
      id: tf-other-stuff
      run: |
        echo "This one isn't used, even though it's the same variable name"
        echo "Note how the Job output is fetched from a specific step name"
        echo "TF_CHANGES=false" >> $GITHUB_OUTPUT

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    # Run only when there are TF changes
    if: |
      needs.gather-info.outputs.TF_CHANGES == 'true'
    steps:
    - name: Stuff
      id: set-deploy-strategy
      run: |
        echo "hi"  
