# This Action is a proof of concept for using a matrix based on a file iteration
# It reads a directory of files and creates a matrix based on the files in that directory
# I think this is a useful pattern for creating terraform data files and then using them to deploy to multiple environments, but haven't done so yet

name: Matrix based on file iteration

on: workflow_dispatch

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-environment-task.outputs.ENVIRONMENT }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Define deploy locations
      id: set-environment-task
      run: |
        # Read pods from a directory
        ALL_PODS=$(ls -l data/ | grep -Ev 'total' | rev | cut -d " " -f1 | rev | cut -d "." -f 1)
        
        # Format environments list
        ENV_LIST=$(echo "$ALL_PODS" | awk 'NF' | sed "s/^/'/g" | sed "s/$/'/g" | tr '\n' ', ' | sed 's/,$//' | sed 's/^/[/g' | sed 's/$/]/g' | sed 's/,/, /g')
        
        # Write output
        echo "ENVIRONMENT=$ENV_LIST" >> $GITHUB_OUTPUT
  
  batch-deploy:
    needs: set-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.set-environment.outputs.ENVIRONMENT) }}
    steps:
    - name: Deploy to environment
      run: echo "hi mom"