name: Passing variable with masking
on: workflow_dispatch
jobs:
  pass-var:
    runs-on: ubuntu-latest
    steps:
    - name: Set deploy location
      id: set-var
      run: |
        solution_name=dev  
        echo "::add-mask::$solution_name"
        echo "solution_name=$solution_name" >> $GITHUB_ENV

        # Set GitHub Secrets for injecting into terraform
        if [[ $(echo "$solution_name" | grep 'dev-') ]]; then
          tf_plan_vars=-var="\"pfx_password=$pfx_password\""
        elif [[ $(echo "$solution_name" | grep 'stg-') ]]; then
          tf_plan_vars=-var="\"pfx_password=$pfx_password\""
        elif [[ $(echo "$solution_name" | grep 'prd-') ]]; then
          tf_plan_vars=-var="\"pfx_password=$pfx_password\""
        fi
    
    - name: Read deploy location
      id: read-var
      run: |
        if [ -z "$solution_name" ]; then
          echo "No solution_name var set, exiting"
          exit 1
        else
          echo "The solution_name var is set to: $solution_name"
        fi