

name: Passing variable with masking

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: The solution to execute, e.g., A, B, C
        type: string
        default: "A"

jobs:
  pass-var:
    runs-on: ubuntu-latest
    steps:
    - name: Set deploy location
      id: set-var
      run: |
        solution_name=${{ inputs.solution_name }}  
        echo "::add-mask::$solution_name"
        echo "solution_name=$solution_name" >> $GITHUB_ENV

    - name: Read deploy location
      id: read-var
      run: |
        echo "Directly printing the value doesn't work"
        echo "$solution_name"

        # However, deriving the value with logic is sometimes possible
        case $solution_name in
          A)
            echo "Solution A"
            ;;
          B)
            echo "Solution B"
            ;;
          C)
            echo "Solution C"
            ;;
          *)
            echo "Solution name not known"
            ;;
        esac