name: Test passing matrix input statically

on:
  workflow_dispatch:
    inputs:
      environments:
        description: The environments to deploy to
        type: string
        default: "['env1', 'env2', 'env3']"

jobs:
  read-environment:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-environment-task.outputs.ENVIRONMENT }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Define deploy locations
      id: set-environment-task
      run: |
        # This worked with fromJSON() in the batch-deploy job
        ENVIRONMENTS = "${{ inputs.environments }}"
        echo "ENVIRONMENT=$ENVIRONMENTS" >> $GITHUB_OUTPUT
  
  batch-deploy:
    needs: read-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.read-environment.outputs.ENVIRONMENT) }}
    steps:
    - name: Deploy to environment
      run: echo "hi mom"