# This job takes an input and passes it to the first job
# Then it exports that value as an output
# The downstream job (job2-read-var) reads that value as an environmental variable called ENVIRONMENT
# We thenk check to make sure that ENVIRONMENT is set and print it out

name: Passing variable between Jobs

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: The name of the environment to run
        type: string
        default: "foobar"

jobs:
  pass-var:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-var.outputs.ENVIRONMENT }}
    steps:
    - name: Set deploy location
      id: set-var
      run: |
        ENVIRONMENT=${{ inputs.ENVIRONMENT }}  
        echo "The ENVIRONMENT var is: $ENVIRONMENT"
        echo "ENVIRONMENT=$ENVIRONMENT" | tee -a $GITHUB_OUTPUT

  job2-read-var:
    runs-on: ubuntu-latest
    needs: pass-var
    steps:
    - name: Print the deploy location
      env:
        ENVIRONMENT: ${{ needs.pass-var.outputs.ENVIRONMENT }}
      run: |
        if [ -z "$ENVIRONMENT" ]; then
          echo "No ENVIRONMENT var set, exiting"
          exit 1
        else
          echo "The ENVIRONMENT var is set to: $ENVIRONMENT"
        fi
