# This Action calls a child workflow and passes a bool to it
# That child action processes our input, and returns a bool
# We use that bool to control whether to run the next job

name: Recursive Actions - Parent

on:
  workflow_dispatch:
    inputs:
      parent_says_run_job_b:
        description: Should we tell child to run job B?
        type: boolean
        default: false

jobs:
  job_a:
    uses: ./.github/workflows/recursive-actions-child.yml
    with:
      parent_says_run_job_b: ${{ inputs.parent_says_run_job_b }}

  job_b:
    needs: job_a
    if: |
      needs.job_a.outputs.CHILD_SAYS_RUN_JOB_B == true
    runs-on: ubuntu-latest
    steps:
    - name: Echo if we're running Job B
      run: |
        echo "Job B is running"
